{% set name = "vsc-base" %}
{% set version = "3.4.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vsc-base-{{ version }}.tar.gz
  sha256: c3c0ede07b6ebb5daf122cb2967df8a7f689b8416678bdb79ae22ec87b2655e6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - vsc-install >=0.15.2
  run:
    - coloredlogs <6.0
    - future >=0.16.0
    - humanfriendly
    - python >=3.6
    - vsc-install >=0.15.2

test:
  imports:
    - vsc
    - vsc.utils

about:
  home: https://github.com/hpcugent/vsc-base
  summary: Common tools used within our organization. Originally created by the HPC team of Ghent University (http://ugent.be/hpc).
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anthchirp
    - boegel
    - jerowe
